### ISSUE TITLE
Error: No tidy method for objects of class glmerMod 

### ISSUE THREAD

**Issue by michaelcvermeulen** [SydneyBioX/scDC#4]
When running the vignette I am getting the following error:

Error: No tidy method for objects of class glmerMod

This occurs at the end of the fitGLM model function.

**Comment by ycao6928** [comment]
Hi!

Thank you for using scDC! 
Looks like this is a problem with the mice package. 
Please try installing the latest version of mice 

> install.packages("devtools")
devtools::install_github(repo = "amices/mice")

And then load broom.mixed

> library(broom.mixed)

GLM show works then.

**Comment by michaelcvermeulen** [comment]
This appears to have fixed the problem. 
Thank you!
