### ISSUE TITLE
Move deps taiyunkim/scClustBench to a new fork?

### ISSUE THREAD

**Issue by altairwei** [SydneyBioX/scDC#5]
https://github.com/taiyunkim/scClustBench/pull/3

**Comment by altairwei** [comment]
It's very hard to `remotes::install_github("SydneyBioX/scDC")` because of {scClustBench}. I have noticed that @YingxinLin made a PR to add pkg imports to {scClustBench}. I think it will be easier to install {scDC} if you change "taiyunkim/scClustBench" to "SydneyBioX/scClustBench".

**Comment by ycao6928** [comment]
Hi altairwei, 

Thanks for pointing it out! I have fixed this.

**Comment by altairwei** [comment]
Another suggestion: add `biocViews: SingleCell` to the end of DESCRIPTION. Since {scran} is a Bioconductor package, `remotes::install_github()` will automatically install {scran} from Bioconductor if we make this change.

**Comment by ycao6928** [comment]
![image](https://user-images.githubusercontent.com/25694939/143572947-a8664e2d-2ffa-4394-bb66-e20f0572f30e.png)

Wow fixed.

**Comment by altairwei** [comment]
I am testing these changes and hope they will make the installation of {scDC} easier.

**Comment by altairwei** [comment]
> I am testing these changes and hope they will make the installation of {scDC} easier.

worked!
