### ISSUE TITLE
bimodal distribution of proportion estimates

### ISSUE THREAD

**Issue by vivekbhr** [SydneyBioX/scDC#7]
Hi scDC team

Thanks for the helpful package. I am looking at a dataset with ~60k cells and 20 cell types from 3 group of samples. After using the  `scDC_noClustering` when I look at the density estimates of proportions I see that for almost all celltypes the proportions have a bimodal distribution. This is leading to large (seemingly ill-fitted)  estimates of CIs. Is there any reason you'd think of this happening?

![image](https://user-images.githubusercontent.com/8420267/154119236-ac7e9158-eadb-46bf-81ef-7fe875c50aa9.png)

**Comment by vivekbhr** [comment]
@ycao6928 @YingxinLin I would appreciate any input on this

**Comment by ycao6928** [comment]
Hi vivekbhr,

Thank you for trying out our package!
You mentioned you have three groups of samples, as in three conditions? 
Unfortunately we have developed the package for testing the difference between two conditions only... 

Best regards,
Yue

**Comment by vivekbhr** [comment]
@ycao6928 If I follow your paper and the package vignette I see that you allow multiple subjects, where subjects are "sample_condition" and the "condition" is only used later when fitting the GLM. If  I construct my data in the same way, and I simply look at the difference in proportions, I get the plot above. I haven't done the GLM yet.

**Comment by vivekbhr** [comment]
I found the issue. . It comes up when there are categories with few cells in the data.. setting a threshold to the number of cells fixed it
